#! /bin/bash

#for i in $@; do echo "\$@ $i"; done
#for i in $*; do echo "\$* $i"; done
#for i in "$@"; do echo "\"\$@\" $i"; done
#for i in "$*"; do echo "\"\$*\" $i"; done

IFS=','

echo "El script $0 recibe $# argumentos los cuales son $*"
echo "El script $0 recibe $# argumentos los cuales son $@"
