#! /bin/bash

# Funciones que implementan un movimiento en pila
# por los directorios
# Funcion que recibe en $1 el directorio al que cambiar,
# cambia y lo almacena en la pila PILADIR
function ira {
	if [ -z "$1" ]; then
		echo "Use ira <directorio>"
		return 1
	fi
	if [ "$1" -ef "$PWD" ]; then
		echo "Ya esta en el directorio $PWD"
		return 2
	fi
	if [ \( -d "$1" \) -a \( -x "$1" \) ]; then
		cd $1
		PILADIR="$1 ${PILADIR:-$OLDPWD}"
		echo $PILADIR
	else
		echo "Directorio $1 no valido"
	fi
}


function volver {
	if [ -n "$PILARDIR" ] ; then
		PILADIR=${PILADIR#* }
		cd ${PILADIR%% *}
		echo $PILADIR
	else
		echo "La pila esta vacia, no se cambio de directorio"
	fi
}
